result_new:
    path: /new/{survey}
    defaults: { _controller: result_controller:newAction }
result_next:
    path: /next/{surveyItem}/{result}
    defaults: { _controller: result_controller:nextAction }
    methods: [ POST ]
result_prev:
    path: /prev/{surveyItem}/{result}
    defaults: { _controller: result_controller:prevAction }
    methods: [ POST ]
result_first:
    path: /first/{survey}
    defaults: { _controller: result_controller:firstAction }
    methods: [ POST ]
result_last:
    path: /last/{surveyItem}/{result}
    defaults: { _controller: result_controller:lastAction }
    methods: [ POST ]
