survey_index:
    path: /
    defaults: { _controller: survey_controller:indexAction }

survey_edit:
    path: /edit/{id}
    defaults: { _controller: survey_controller:editAction }

survey_item_form:
    path: /item/{id}
    defaults: { _controller: survey_controller:surveyItemFormAction }

survey_evaluations:
    path: /evaluations/{survey}
    defaults: { _controller: survey_controller:evaluationsAction }
