survey_index:
    path: /
    defaults: { _controller: survey_controller:indexAction }

survey_new:
    path: /new
    defaults: { _controller: survey_controller:newAction }

survey_edit:
    path: /edit/{id}
    defaults: { _controller: survey_controller:editAction }

survey_evaluations:
    path: /evaluations/{survey}
    defaults: { _controller: survey_controller:evaluationsAction }
