fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: survey_index
        permanent: false
        ignoreAttributes: true

survey:
    resource: "routing_survey.yml"
    prefix:     /survey

result:
    resource: "routing_result.yml"
    prefix: /result

survey_item:
    resource: "routing_survey_item.yml"
    prefix:     /survey-item

choice:
    resource: "routing_choice.yml"
    prefix:     /choice

bunny_result_evaluation:
    path: /result/evaluation/bunny/{result}
    defaults: { _controller: app.controller.bunny_evaluation_controller:evaluateResultAction }

custom_result_evaluation:
    path: /result/evaluation/custom/{result}
    defaults: { _controller: app.controller.custom_evaluation_controller:evaluateResultAction }

user_list:
    path: /user/list
    defaults: { _controller: app.controller.user_controller:listAction }

user_create:
    path: /user/create
    defaults: { _controller: app.controller.user_controller:createAction }

user_edit:
    path: /user/edit/{user}
    defaults: { _controller: app.controller.user_controller:editAction }

allowed_origin_list:
    path: /origin/list
    defaults: { _controller: app.controller.allowed_origin_controller:listAction }

allowed_origin_create:
    path: /origin/create
    defaults: { _controller: app.controller.allowed_origin_controller:createAction }

allowed_origin_edit:
    path: /origin/edit/{allowedOrigin}
    defaults: { _controller: app.controller.allowed_origin_controller:editAction }
