fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: survey_index
        permanent: false
        ignoreAttributes: true

pm_surveythor:
    resource: "@PMSurveythorBundle/Resources/config/routing.yml"
    prefix:   /

result_evaluation:
    path: /result/evaluation/{id}
    defaults: { _controller: app.controller.evaluation_controller:evaluateResultAction }

user_list:
    path: /user/list
    defaults: { _controller: app.controller.user_controller:listAction }

user_create:
    path: /user/create
    defaults: { _controller: app.controller.user_controller:createAction }

user_edit:
    path: /user/edit/{user}
    defaults: { _controller: app.controller.user_controller:editAction }

allowed_origin_list:
    path: /origin/list
    defaults: { _controller: app.controller.allowed_origin_controller:listAction }

allowed_origin_create:
    path: /origin/create
    defaults: { _controller: app.controller.allowed_origin_controller:createAction }

allowed_origin_edit:
    path: /origin/edit/{allowedOrigin}
    defaults: { _controller: app.controller.allowed_origin_controller:editAction }
