services:
    _defaults:
        autowire: true
        autoconfigure: true

    app.controller.bunny_evaluation_controller:
        class: AppBundle\Controller\Evaluation\BunnyEvaluationController
    app.controller.custom_evaluation_controller:
        class: AppBundle\Controller\Evaluation\CustomEvaluationController
    app.controller.user_controller:
        class: AppBundle\Controller\UserController
    app.controller.allowed_origin_controller:
        class: AppBundle\Controller\AllowedOriginController
    app.controller.survey_controller:
        class: AppBundle\Controller\SurveyController
    app.controller.result_controller:
        class: AppBundle\Controller\ResultController
    app.controller.survey_item_controller:
        class: AppBundle\Controller\SurveyItemController
    app.controller.choice_controller:
        class: AppBundle\Controller\ChoiceController
    app.controller.embed_controller:
        class: AppBundle\Controller\EmbedController