survey:
    resource: "@PMSurveythorBundle/Resources/config/routing/survey.yml"
    prefix:     /survey

result:
    resource: "@PMSurveythorBundle/Resources/config/routing/result.yml"
    prefix: /result

survey_item:
    resource: "@PMSurveythorBundle/Resources/config/routing/survey-item.yml"
    prefix:     /surveyitem
