imports:
    - { resource: services_controller.yml }
    - { resource: services_repository.yml }

services:
    app.event_listener.response_header_listener:
        class:     AppBundle\EventListener\ResponseHeaderListener
        autowire:  true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 1 }

    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
