services:
    survey_controller:
        class: PM\SurveythorBundle\Controller\SurveyController
        arguments:
            - "@survey_repository"

    result_controller:
        class: PM\SurveythorBundle\Controller\ResultController
        arguments:
            - "@result_ready_subscriber"
            - "@form.factory"
            - "@result_repository"

    survey_item_controller:
        class: PM\SurveythorBundle\Controller\SurveyItemController
