PM\SurveythorBundle\Entity\Condition:
    type: entity
    table: item_condition
    repositoryClass: PM\SurveythorBundle\Repository\ConditionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        isNegative:
            type: boolean

    manyToOne:
        item:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItem
            inversedBy: conditions
        question:
            targetEntity: PM\SurveythorBundle\Entity\Question

    manyToMany:
        choices:
            targetEntity: PM\SurveythorBundle\Entity\Choice

    lifecycleCallbacks: {  }
