PM\SurveythorBundle\Entity\Question:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\QuestionRepository

    fields:
        text:
            type: text
        type:
            type: string
            length: 255


    oneToMany:
        choices:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            mappedBy: question
            cascade:
                - persist
            orderBy: { 'sortOrder' : 'ASC'}

    manyToOne:
        parentChoice:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            inversedBy: childQuestions

        template:
            targetEntity: PM\SurveythorBundle\Entity\QuestionTemplate

        childrenTemplate:
            targetEntity: PM\SurveythorBundle\Entity\QuestionTemplate

    lifecycleCallbacks:
        prePersist: [ setInitialSortOrder ]
