PM\SurveythorBundle\Entity\Question:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\QuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        type:
            type: string
            length: 255

    oneToMany:
        answers:
            targetEntity: PM\SurveythorBundle\Entity\Answer
            mappedBy: question
            cascade:
                - persist

    manyToOne:
        survey:
            targetEntity: PM\SurveythorBundle\Entity\Survey
            inversedBy: questions

        parentAnswer:
            targetEntity: PM\SurveythorBundle\Entity\Answer
            inversedBy: childQuestions

    lifecycleCallbacks: {  }
