PM\SurveythorBundle\Entity\Question:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\QuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        type:
            type: string
            length: 255
        sortOrder:
            type: integer

    oneToMany:
        choices:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            mappedBy: question
            cascade:
                - persist
            orderBy: { 'sortOrder' : 'ASC'}

    manyToOne:
        survey:
            targetEntity: PM\SurveythorBundle\Entity\Survey
            inversedBy: questions

        parentChoice:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            inversedBy: childQuestions

        template:
            targetEntity: PM\SurveythorBundle\Entity\QuestionTemplate
            inversedBy: questions

        childrenTemplate:
            targetEntity: PM\SurveythorBundle\Entity\QuestionTemplate
            inversedBy: questions

    lifecycleCallbacks:
        prePersist: [ setInitialSortOrder ]
