PM\SurveythorBundle\Entity\Result:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\ResultRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetimetz

    oneToMany:
        resultItems:
            targetEntity: PM\SurveythorBundle\Entity\ResultItem
            mappedBy: result
            cascade:
                - persist
                - merge
                - detach
            orderBy: { 'sortOrder' : 'ASC'}

    manyToOne:
        survey:
            targetEntity: PM\SurveythorBundle\Entity\Survey
            inversedBy: results

    lifecycleCallbacks:
        prePersist: [ setCreatedValue ]
