PM\SurveythorBundle\Entity\Survey:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\SurveyRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true

    oneToMany:
        surveyItems:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItem
            mappedBy: survey
            cascade:
                - persist
            orderBy: { 'sortOrder' : 'ASC'}
        resultRanges:
            targetEntity: PM\SurveythorBundle\Entity\ResultRange
            mappedBy: survey
            cascade:
                - persist
        results:
            targetEntity: PM\SurveythorBundle\Entity\Result
            mappedBy: survey
            cascade:
                - persist

    lifecycleCallbacks: {}

