PM\SurveythorBundle\Entity\SurveyItems\Question:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\QuestionRepository

    fields:
        text:
            type: text
        type:
            type: string
            length: 255

    oneToMany:
        choices:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            mappedBy: question
            cascade:
                - persist
                - remove
            orderBy: { 'sortOrder' : 'ASC'}

    manyToOne:
        questionTemplate:
            targetEntity: PM\SurveythorBundle\Entity\QuestionTemplate

    lifecycleCallbacks: {}
