surveyitem_new:
    path: /new/{survey}/{type}
    defaults: { _controller: app.controller.survey_item_controller:newAction }
surveyitem_update:
    path: /update/{item}
    defaults: { _controller: app.controller.survey_item_controller:updateAction }
itemgroup_add_item:
    path: /group-additem/{survey}/{type}
    defaults: { _controller: app.controller.survey_item_controller:itemGroupAddItemAction}
surveyitem_form:
    path: /form/{item}
    defaults: { _controller: app.controller.survey_item_controller:formAction }
surveyitem_set_sortorder:
    path: /sortorder/{item}
    defaults: { _controller: app.controller.survey_item_controller:setSortOrderAction}
surveyitem_remove:
    path: /remove/{item}
    defaults: { _controller: app.controller.survey_item_controller:removeAction }

